#!/bin/sh
set -eu

lb config \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer false \
  --archive-areas "main" \
  --apt-recommends false \
  --apt-indices false \
  --bootappend-live "boot=live components quiet splash" \
  --linux-packages "linux-image-amd64" \
  --bootloaders "grub-pc grub-efi syslinux" \
  --chroot-squashfs-compression-type xz \
  --chroot-squashfs-compression-level 9 \
  --initramfs-compression xz \
  --chroot-filesystem squashfs \
  --iso-application "NSK OS" \
  --iso-publisher "NSK" \
  --iso-volume "NSK_OS_0.3" \
  --iso-preparer "live-build" \
  --firmware-binary false \
  --firmware-chroot false \
  --memtest none