conky.config = {
  alignment = 'top_right',
  background = false,
  border_width = 0,
  cpu_avg_samples = 2,
  default_color = '#17304f',
  double_buffer = true,
  draw_borders = false,
  draw_graph_borders = false,
  draw_outline = false,
  draw_shades = false,
  extra_newline = false,
  font = 'Inter:size=10',
  gap_x = 18,
  gap_y = 26,
  minimum_height = 280,
  minimum_width = 220,
  own_window = true,
  own_window_argb_visual = true,
  own_window_argb_value = 205,
  own_window_type = 'normal',
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  own_window_transparent = false,
  pad_percents = 2,
  update_interval = 1,
  use_xft = true,
  xftalpha = 0.95,
};
conky.text = [[
${voffset 8}${font Inter:bold:size=30}${time %H:%M}${font}
${font Inter:size=11}${time %a, %d %b %Y}${font}
${hr 1}
${font Inter:bold:size=11}▣  CPU${font}${alignr}${cpu}%
${execbar 1}${voffset 5}
${font Inter:bold:size=11}▣  RAM${font}${alignr}${memperc}%
${membar 6,220}
${voffset 5}${font Inter:bold:size=11}▣  Disk${font}${alignr}${fs_used_perc /}%
${fs_bar 6,220 /}
]];
