/**
 * NSK OS v0.3 - PS/2 Mouse Driver Header (Phase 3)
 * IRQ 12 packet decoding, sub-pixel tracking with a smooth acceleration curve,
 * and anti-aliased alpha-blended cursor rendering.
 */
#ifndef NSK_MOUSE_H
#define NSK_MOUSE_H

#include "types.h"

#define MOUSE_BTN_LEFT   (1 << 0)
#define MOUSE_BTN_RIGHT  (1 << 1)
#define MOUSE_BTN_MIDDLE (1 << 2)

// Cursor sprite geometry (generated by tools/gen_cursor.py - mouse.c asserts these match).
// The sprite is drawn so that its arrow tip (the hot spot) lands exactly on the pointer
// position, so the dirty rectangle of a cursor at (x, y) is:
//   (x - MOUSE_CURSOR_HOT_X, y - MOUSE_CURSOR_HOT_Y, MOUSE_CURSOR_W, MOUSE_CURSOR_H)
#define MOUSE_CURSOR_W      24
#define MOUSE_CURSOR_H      34
#define MOUSE_CURSOR_HOT_X  2
#define MOUSE_CURSOR_HOT_Y  2

typedef struct {
    int  x;
    int  y;
    int  prev_x;
    int  prev_y;
    uint8_t buttons;
    uint8_t prev_buttons;
    bool moved;     // sticky until mouse_get_state() reads it
    bool clicked;   // left button pressed  - reported exactly once
    bool released;  // left button released - reported exactly once
} mouse_state_t;

void mouse_init(uint32_t screen_width, uint32_t screen_height);
void mouse_get_state(mouse_state_t* out_state);
bool mouse_has_pending_event(void);
void mouse_draw_cursor(int x, int y);

#endif /* NSK_MOUSE_H */
