#!/usr/bin/env python3
"""
NSK OS - wallpaper asset generator.

Converts a wallpaper image (e.g. HOME.PNG) into:
  1. kernel/wallpaper_home.h  - 24-bit RGB (0x00RRGGBB) array embedded in the kernel
  2. (optional) a high quality JPEG used by the React preview in src/assets/images

Usage:
  python3 tools/gen_wallpaper.py HOME.PNG
  python3 tools/gen_wallpaper.py HOME.PNG --web src/assets/images/wallpaper_nsk_1790838490517.jpg

Requires: Pillow
"""
import argparse
import os
import sys

from PIL import Image

KERNEL_W = 768
KERNEL_H = 512      # 3:2, same aspect as the 1536x1024 reference UI
EDGE_CROP = 3       # uploaded PNG has a 1-2 px semi-transparent rounded border


def load_opaque(path):
    img = Image.open(path)
    img.load()
    if img.mode != "RGBA":
        return img.convert("RGB")

    w, h = img.size
    img = img.crop((EDGE_CROP, EDGE_CROP, w - EDGE_CROP, h - EDGE_CROP))
    lo = img.getchannel("A").getextrema()[0]
    if lo < 250:
        print(f"[warn] cropped image still has alpha down to {lo}; flattening on its edge colour")
    bg = Image.new("RGBA", img.size, img.getpixel((img.width // 2, 0)))
    return Image.alpha_composite(bg, img).convert("RGB")


def write_header(img, out_path):
    small = img.resize((KERNEL_W, KERNEL_H), Image.LANCZOS)
    px = small.load()

    lines = []
    for y in range(KERNEL_H):
        row = ",".join("0x%02X%02X%02X" % px[x, y] for x in range(KERNEL_W))
        lines.append(row + ",")

    with open(out_path, "w") as f:
        f.write("// Auto-generated by tools/gen_wallpaper.py - do not edit by hand.\n")
        f.write("// Source: HOME.PNG (Bloom silk wallpaper), 24-bit RGB, 0x00RRGGBB per pixel.\n")
        f.write("#ifndef NSK_WALLPAPER_HOME_H\n#define NSK_WALLPAPER_HOME_H\n\n")
        f.write("#define WALLPAPER_W %d\n#define WALLPAPER_H %d\n\n" % (KERNEL_W, KERNEL_H))
        f.write("static const uint32_t home_wallpaper_rgb[WALLPAPER_W * WALLPAPER_H] = {\n")
        f.write("\n".join(lines))
        f.write("\n};\n\n#endif /* NSK_WALLPAPER_HOME_H */\n")
    print(f"[ok] {out_path}  ({os.path.getsize(out_path) // 1024} KB source, "
          f"{KERNEL_W * KERNEL_H * 4 // 1024} KB in kernel image)")
    return small


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--out", default="kernel/wallpaper_home.h")
    ap.add_argument("--web", action="append", default=[],
                    help="also write a JPEG preview here (can be repeated)")
    ap.add_argument("--preview", help="write the downscaled kernel image as PNG for checking")
    args = ap.parse_args()

    img = load_opaque(args.image)
    print(f"[info] source {img.size[0]}x{img.size[1]} after edge crop")
    small = write_header(img, args.out)

    for p in args.web:
        img.save(p, "JPEG", quality=92, optimize=True, subsampling=0)
        print(f"[ok] {p}")
    if args.preview:
        small.save(args.preview)


if __name__ == "__main__":
    sys.exit(main())
