#!/usr/bin/env python3
"""
NSK OS - anti-aliased mouse cursor generator.

Renders a Fluent-style arrow (white fill, thin dark outline, soft drop shadow)
with 8x supersampling and writes include/cursor_sprite.h as straight-alpha ARGB.

Usage:
  python3 tools/gen_cursor.py
  python3 tools/gen_cursor.py --preview /tmp/cursor_preview.png

Requires: Pillow
"""
import argparse
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

# Keep these in sync with MOUSE_CURSOR_* in include/mouse.h (mouse.c asserts it).
W, H = 24, 34
HOT_X, HOT_Y = 2, 2     # where the arrow tip sits inside the sprite
SS = 8                  # supersampling factor

# Arrow outline, in pixels, tip at (0, 0)
ARROW = [(0.0, 0.0), (0.0, 20.8), (4.7, 16.4), (8.3, 24.7),
         (11.6, 23.3), (8.1, 15.2), (14.3, 15.2)]

OUTLINE_PX = 1.5        # total stroke width, half inside / half outside the arrow
SHADOW_DX, SHADOW_DY = 1.5, 2.0
SHADOW_BLUR = 2.0
SHADOW_ALPHA = 0.38


def render():
    big = (W * SS, H * SS)
    pts = [((HOT_X + x) * SS, (HOT_Y + y) * SS) for x, y in ARROW]

    poly = Image.new("L", big, 0)
    ImageDraw.Draw(poly).polygon(pts, fill=255)

    stroke = Image.new("L", big, 0)
    ImageDraw.Draw(stroke).line(pts + [pts[0]], fill=255,
                                width=int(round(OUTLINE_PX * SS)), joint="curve")

    black_mask = ImageChops.lighter(poly, stroke)       # arrow + outer half of the stroke
    white_mask = ImageChops.subtract(poly, stroke)      # arrow minus inner half of the stroke

    # Soft shadow: offset + blurred copy of the black silhouette
    shadow = Image.new("L", big, 0)
    shadow.paste(black_mask, (int(SHADOW_DX * SS), int(SHADOW_DY * SS)))
    shadow = shadow.filter(ImageFilter.GaussianBlur(SHADOW_BLUR * SS / 2))
    shadow = shadow.point(lambda v: int(v * SHADOW_ALPHA))

    canvas = Image.new("RGBA", big, (0, 0, 0, 0))
    canvas.alpha_composite(Image.merge("RGBA", (Image.new("L", big, 0),) * 3 + (shadow,)))
    canvas.alpha_composite(Image.merge("RGBA", (Image.new("L", big, 20),) * 3 + (black_mask,)))
    canvas.alpha_composite(Image.merge("RGBA", (Image.new("L", big, 255),) * 3 + (white_mask,)))

    # Downsample with premultiplied alpha so edges don't pick up dark fringes
    pm = Image.new("RGBA", big)
    src = canvas.load()
    dst = pm.load()
    for y in range(big[1]):
        for x in range(big[0]):
            r, g, b, a = src[x, y]
            dst[x, y] = (r * a // 255, g * a // 255, b * a // 255, a)
    small = pm.resize((W, H), Image.BOX)

    out = Image.new("RGBA", (W, H))
    sp, op = small.load(), out.load()
    for y in range(H):
        for x in range(W):
            r, g, b, a = sp[x, y]
            if a == 0:
                op[x, y] = (0, 0, 0, 0)
            else:
                op[x, y] = (min(255, r * 255 // a), min(255, g * 255 // a),
                            min(255, b * 255 // a), a)
    return out


def write_header(img, path):
    px = img.load()
    rows = []
    for y in range(H):
        vals = []
        for x in range(W):
            r, g, b, a = px[x, y]
            vals.append("0x%08X" % ((a << 24) | (r << 16) | (g << 8) | b))
        rows.append(",".join(vals) + ",")
    with open(path, "w") as f:
        f.write("// Auto-generated by tools/gen_cursor.py - do not edit by hand.\n")
        f.write("// Anti-aliased arrow cursor, straight-alpha ARGB (0xAARRGGBB).\n")
        f.write("#ifndef NSK_CURSOR_SPRITE_H\n#define NSK_CURSOR_SPRITE_H\n\n")
        f.write("#define CURSOR_SPRITE_W %d\n#define CURSOR_SPRITE_H %d\n" % (W, H))
        f.write("#define CURSOR_SPRITE_HOT_X %d\n#define CURSOR_SPRITE_HOT_Y %d\n\n" % (HOT_X, HOT_Y))
        f.write("static const uint32_t cursor_sprite_argb[CURSOR_SPRITE_W * CURSOR_SPRITE_H] = {\n")
        f.write("\n".join(rows))
        f.write("\n};\n\n#endif /* NSK_CURSOR_SPRITE_H */\n")
    print(f"[ok] {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="include/cursor_sprite.h")
    ap.add_argument("--preview")
    args = ap.parse_args()

    img = render()
    write_header(img, args.out)

    if args.preview:
        zoom = 12
        bg = Image.new("RGBA", (W * zoom * 3, H * zoom), (0, 0, 0, 0))
        tiles = [(166, 183, 205), (240, 244, 250), (30, 41, 59)]
        big = img.resize((W * zoom, H * zoom), Image.NEAREST)
        for i, col in enumerate(tiles):
            tile = Image.new("RGBA", (W * zoom, H * zoom), col + (255,))
            tile.alpha_composite(big)
            bg.paste(tile, (i * W * zoom, 0))
        bg.convert("RGB").save(args.preview)
        print(f"[ok] preview {args.preview}")


if __name__ == "__main__":
    sys.exit(main())
