name: Build NSK OS ISO

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y             build-essential             bc bison flex             cpio file rsync             unzip wget curl             libelf-dev             grub-pc-bin grub-common             xorriso             python3

      - name: Build ISO
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Check ISO
        run: |
          ls -lh dist/nsko-x86_64.iso
          test $(stat -c%s dist/nsko-x86_64.iso) -le $((300*1024*1024))

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: NSK-OS-x86_64-ISO
          path: dist/nsko-x86_64.iso
          if-no-files-found: error
